### ISSUE TITLE
求助，使用遇到问题，是中文路径或文件名引起的么？

### ISSUE THREAD

**Issue by ChenRuihua** [tobyqin/photodup#3]
使用时遇到如下问题。
照片目录带有中文，照片文件名也有中文。
是这个原因引起的么？

> 2019-06-23 22:14:10,094 INFO    : Processing: 10000 / 83063
Traceback (most recent call last):
  File "scan.py", line 102, in <module>
    save_files_to_db(dir, scan_file_type)
  File "scan.py", line 62, in save_files_to_db
    walk_dir(from_dir, save_action)
  File "scan.py", line 17, in walk_dir
    action_on_file(full_path)
  File "scan.py", line 50, in save_action
    if db.is_existed(file):
  File "/volume1/homes/oran/Drive/Code/photodup/db.py", line 45, in is_existed
    cursor.execute('SELECT COUNT(*) FROM photo WHERE path = ? AND existed = 1', (file_path,))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by tobyqin** [comment]
印象中对中文支持是没问题的，你的python版本多少？最好3.5以上。

**Comment by tobyqin** [comment]
你看我项目截图里路径和文件名都是有中文的
